version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - checkout
      - run:
          name: Install dependency
          command: npm install
      - run:
          name: Run test
          command: npm run test
      - run: node --version